[workspace]
members = ["xtask", "common/*"]
exclude = ["firmware"]
default-members = ["xtask"]
resolver = "2"

[workspace.package]
authors = ["storycraft <storycraft@pancake.sh>"]
license = "MIT OR Apache 2.0"
