[build]
target = "atmega32u4.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[profile.dev]
panic = "abort"
debug = false
debug-assertions = false
overflow-checks = false
opt-level = 'z'
codegen-units = 1
lto = true
strip = true

[profile.release]
panic = "abort"
opt-level = 'z'
codegen-units = 1
lto = true
strip = true
