[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
authors = ["storycraft <storycraft@pancake.sh>"]
license = "MIT OR Apache 2.0"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
