[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
authors = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
cargo_metadata = "0.18.1"
