[build]
pre_cmds = []
post_cmds = [
    "avr-objcopy -O ihex {{exec.full_path}} {{exec.directory}}{{path.separator}}{{exec.name}}.hex"
]

[deploy]
cmds = [
    "dfu-programmer atmega32u4 erase --force",
    "dfu-programmer flash --force {{exec.directory}}{{path.separator}}{{exec.name}}.hex",
    "dfu-programmer atmega32u4 reset",
]
